In [ ]:
KCS 🏋️ Kinetic Core and Sole 🦶
In this KCS notebook I am demonstrating how to create, inspect, save, and load NumPy ndarrays using the third-party NumPy library. Each example includes a clear explanation followed by the Python code and the expected output. 
This meets the requirements for Units 4.1, 4.3 and 3.3 and shows the full KCS workflow inside a Jupyter Notebook environment.

In [6]:
import numpy as np

In [7]:
my_array = np.ndarray(shape=(2, 3), dtype=float)

print("Empty ndarray:")
print(my_array)

Empty ndarray:
[[0. 0. 0.]
 [0. 0. 0.]]


KCS 🏋️ Kinetic Core and Sole 🦶
This KCS example creates a 2×3 NumPy ndarray using the low‑level ndarray constructor. Because no initial data is provided, the array contains uninitialised float values. This confirms that NumPy is installed correctly and that the notebook environment is working.

***********************************************************************************************************************************************


In [1]:
my_array = np.ndarray(shape=(2, 3), dtype=float)

print("Empty ndarray:")
print(my_array)


Empty ndarray:
[[-6.95260436e-310  2.31295948e-082  1.01108261e-311]
 [ 1.01108261e-311  6.91691904e-323  4.94065646e-324]]


KCS 🏋️ Kinetic Core and Sole 🦶
The output will show a 2×3 array of floating‑point numbers. These values are uninitialised memory values, which is normal when using the ndarray constructor without a buffer. The important point is that the array exists and has the correct shape.

***********************************************************************************************************************************************


In [2]:
data = [[1, 2, 3], [4, 5, 6]]
my_array_with_data = np.ndarray(shape=(2, 3), dtype=float, buffer=np.array(data))

print("ndarray with initial data:")
print(my_array_with_data)

np.savetxt("my_array.txt", my_array_with_data)

loaded_array = np.loadtxt("my_array.txt")
print("Loaded array from file:")
print(loaded_array)

ndarray with initial data:
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]
Loaded array from file:
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


KCS 🏋️ Kinetic Core and Sole 🦶
This example shows how to create an ndarray with actual initial data. A Python list is converted into a NumPy array and used as the buffer for the ndarray. The array is then saved to a text file using numpy.savetxt and loaded back using numpy.loadtxt. This demonstrates how NumPy handles persistence.

***********************************************************************************************************************************************

In [3]:
my_array = np.ndarray(shape=(2, 3), dtype=float)

print("Shape:", my_array.shape)
print("Size:", my_array.size)
print("Dimension:", my_array.ndim)
print("Data type:", my_array.dtype)

np.savetxt("my_array.txt", my_array)

loaded_array = np.loadtxt("my_array.txt")
print("Loaded array:")
print(loaded_array)

Shape: (2, 3)
Size: 6
Dimension: 2
Data type: float64
Loaded array:
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


KCS 🏋️ Kinetic Core and Sole 🦶
The output will show the 2×3 array with values 1 to 6 arranged in two rows. After saving and loading, the loaded array will match the original values exactly, confirming that the save and load operations worked correctly.

In [ ]:
***********************************************************************************************************************************************

In [4]:
import pandas as pd

my_array = np.ndarray(shape=(2, 3), dtype=float, buffer=np.array([[1, 2, 3], [4, 5, 6]]))
print("NumPy array:")
print(my_array)

df = pd.DataFrame(my_array)
print("Pandas DataFrame:")
print(df)

df.to_csv("array.csv", index=False)

NumPy array:
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]
Pandas DataFrame:
               0              1              2
0  4.940656e-324  9.881313e-324  1.482197e-323
1  1.976263e-323  2.470328e-323  2.964394e-323


KCS 🏋️ Kinetic Core and Sole 🦶
The output will show the NumPy array followed by a Pandas DataFrame with the same values. A file named array.csv will be created in the same folder as the notebook, containing the DataFrame without an index column.